language: ruby
rvm: 2.6.3
install: bundle install
script: bundle exec jekyll build && bundle exec htmlproofer ./_site --check-favicon --check-html --assume-extension --internal-domains r3dlin3.github.io --url-ignore http://localhost:8000,http://localhost:8000/,https://\$appName.scm.azurewebsites.net/webssh/host
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local-dir: _site
  target-branch: master
  on:
    branch: dev

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build