title: A bit of everything
description: A bit of everything
author:      r3dLiN3
url:         "https://r3dlin3.github.com"
encoding: utf-8
date_format: '%Y-%m-%d'
exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font

paginate:     4
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty