title: A bit of everything
description: A bit of everything
author: r3dLiN3
url: "https://r3dlin3.github.com"
encoding: utf-8
date_format: '%Y-%m-%d'
exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=rouge
    - icons=font

sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-asciidoc
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
#theme: jekyll-theme-type
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty

excerpt_separator: <!--more-->

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: A bit of everything
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  #gravatar: # Email MD5 hash
  description: "A bit of everything"

  # Header and footer text
  #header_text: >
  #   <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
  #
  #   <p>Remove all header text in <code>_config.yml</code> to disable this feature.</p>
  #header_text_feature_image:
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <i class="fa fa-heart" aria-hidden="true" style="color:Tomato"/></i>

  # Icons
  rss: true
  #email_address: # Full email address, e.g. "sam@example.com"
  #behance:
  #bitbucket:
  #dribbble:
  #facebook:
  #flickr:
  #gitlab:
  github: "r3dlin3"
  #google_plus:
  #instagram:
  #linkedin:  # Full URL
  #pinterest:
  #reddit:
  #soundcloud:
  #stack_exchange:  # Full URL
  #steam:
  #tumblr:
  #twitter: "twitter"
  #wordpress:
  #youtube:

  # Scripts
  #google_analytics: # Tracking ID, e.g. "UA-000000-01"
  #disqus_shortname:
  katex: false # Enable if using math markup
  search: false # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Suivre sur RSS"
  str_email: "Email"
  str_next_post: "Article suivant"
  str_previous_post: "Article précédent"
  str_next_page: "Suivant"
  str_previous_page: "Précédent"
  str_continue_reading: "Continuer la lecture"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "Aucun résultat trouvé."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

highlighter: rouge

