= README

image:https://travis-ci.org/r3dlin3/r3dlin3.github.io.svg?branch=dev[]

Rappel de quelques commandes

== Installation

    bundle install

== Affichage des pages en local

Pour servir localement les pages :

    bundle exec jekyll serve
    
Avec les brouillons :
    
    bundle exec jekyll serve --drafts

== FAQ Jekyll/Asciidoc

=== Faire référence à un autre article

    link:{{ site.baseurl }}{% post_url 2019-12-30-sonarqube-docker-windows %}[SonarQube sur son poste]

=== Bloc de code source

.azure-pipelines.yml
[source,yaml]
----
----


```powershell
```

=== HTML Proofer

Réf: https://github.com/18F/html-proofer-docker

    bundle exec jekyll clean
    bundle exec jekyll build
    docker run --rm -v $pwd\_site:/mounted-site 18fgsa/html-proofer /mounted-site --check-favicon --check-html --assume-extension --internal-domains r3dlin3.github.io --url-ignore "/localhost:8000/,https://\$appName.scm.azurewebsites.net/webssh/host"
    
    docker run --rm -v %cd%\_site:/mounted-site 18fgsa/html-proofer /mounted-site --check-favicon --check-html --assume-extension --internal-domains r3dlin3.github.io --url-ignore "/localhost:8000/,https://\$appName.scm.azurewebsites.net/webssh/host"