= Suivre le tutorial d'Udacity sur Kubernetes avec Azure
:showtitle:
:page-navtitle: Suivre le tutorial d'Udacity sur Kubernetes avec Azure
:page-excerpt: Comment suivre le tutorial d'Udacity avec une souscription Azure?
//:page-root: ../../../
:page-tags: [kubernetes,azure,aks,docker,microservices]
:experimental:

Udacity propose un https://www.udacity.com/course/scalable-microservices-with-kubernetes--ud615[cours gratuit] sur Docker, les microservices et Kubernetes (en anglais). Tout est très bien décrit, y compris les commandes mais cela se base (naturellement) sur Google Container Engine (GKE).

Disposant déjà d'une souscription Azure et Azure proposant également une offre managée sur Kubernetes : Azure Container Service (AKS).

Azure disposant également d'un Registry privé (Azure Container Registry), ce sera l'occasion de l'utilisé!

Le tutorial fait également largement usage de https://cloud.google.com/shell/docs/[Google Cloud Shell]. Azure dispose également d'un shell: Azure Cloud Shell. Il est même proposé "en plein écran" depuis peu et propose un raccourci vers http://shell.azure.com/bash[bash] ou http://shell.azure.com/powershell[PowerShell].

L'Azure Cloud Shell [line-through]#permet une persistance# a un espace de stockage en étant lié à un Storage Account. Ce sera donc parfait pour créer une image, la publier et autre.

La suite de cet article présente par leçon, étape par étape les adaptations

## Lesson 1: Introduction to Microservices

// Enable Compute Engine and Container Engine APIs

### Etape 5: Get the Source Code
Je fais l'hypothèse que vous avez une souscription Azure et que vous avez démarré un Bash dans http://shell.azure.com/bash[Azure Cloud Shell].
TIP: Sous Windows, utilisez kbd:[Ctrl+Insert] to copy and kbd:[Shift+Insert] to paste. 

Go étant déjà installé, rien à faire ici:

[source,bash]
----
$ go version
go version go1.7 linux/amd64
----

