= Moindre privilège pour packer avec Azure
:page-navtitle: Moindre privilège pour packer avec Azure
:page-excerpt: Contrairement à ce qui est documenter, il est possible de ne pas donner les droits de contributeurs sur la souscription Azure
:page-tags: [packer,azure]
:experimental:
:page-liquid:
:icons: font

== Pourquoi déjà ?

Par défaut, la https://www.packer.io/docs/builders/azure-setup.html#grant-permissions-to-your-application[documentation de packer] indique qu'il faut créer un service principal avec des droits de contributeur sur la souscription.

[NOTE]
il est possible de se passer de service principal en utilisant https://www.packer.io/docs/builders/azure-setup.html#device-login[Device Login]. 
Malheureusement, ce n'est possible que pour un OS cible sous Linux, ce qui n'était pas mon cas.

Il est possible de restreindre les droits de ce service principal à 2 groupes de resource:

* Le groupe de ressource qui va accueillir l'image
* Un groupe de ressource qui va accueillir accueillir les ressources temporaires (VM, interface réseau, disque, VNET)

NOTE: Cette procédure est valable pour packer v1.2.4

== Mise en oeuvre

En fonction que vous lisez https://docs.microsoft.com/en-us/azure/virtual-machines/windows/build-image-with-packer[La doc Microsoft] 
ou https://www.packer.io/docs/builders/azure-setup.html [celle de Packer], vous aurez respectivement la version PowerShell ou Azure CLI.

Pour ma part, je suis parti sur du PowerShell.

=== Connexion à Azure 

Pas de subtilité ici:

    Login-AzureRmAccount

Et au besoin, si vous avez plusieurs souscriptions

    Select-AzureRmSubscription -SubscriptionName <Ma Souscription>

=== Création d'un service principal

La création d'un service principal se fait avec une cmdlet :

    $sp = New-AzureRmADServicePrincipal -DisplayName "Azure Packer" `
        -Password (ConvertTo-SecureString "P@ssw0rd!" -AsPlainText -Force)

=== Création des groupes de ressource

La création de groupe de resource se fait à l'aide de la cmdlet `New-AzureRmResourceGroup`.
Il est recommandable

----
$rgName = "rg-my-images"
$rgPackerName = "rg-packer"
$location = "West Europe"
New-AzureRmResourceGroup -Name $rgName -Location $location
New-AzureRmResourceGroup -Name $rgPackerName -Location $location
----

NOTE: la cmdlet `Get-AzureRmLocation` donne la liste des localisations possibles.

=== Droits sur les groupes de ressource
le rôle de contributeur doit être attribué juste sur les 2 groupes de ressource.

    New-AzureRmRoleAssignment -RoleDefinitionName Contributor -ServicePrincipalName $sp.ApplicationId -ResourceGroupName $rgName
    New-AzureRmRoleAssignment -RoleDefinitionName Contributor -ServicePrincipalName $sp.ApplicationId -ResourceGroupName $rgPackerName

== Script tout-en-un

J'ai préparé un petit script tout-en-un:

{% gist 11733d072c25c661b3237ba65dc07d69 setup-azure.ps1 %}

Il produira une structure JSON de la sorte:
----
{
    "tenant_id": "c18XXXXX-XXXX-XXXX-XXXX-XXXXXXXXX90a",
    "subscription_id": "a02XXXXX-XXXX-XXXX-XXXX-XXXXXXXXXc54",
    "client_id": "210XXXXX-XXXX-XXXX-XXXX-XXXXXXXXX8f6",
    "client_secret": "J5vbx0nim82qj4iT0efetY4N2sGmAwFA",
    "managed_image_resource_group_name": "rg-my-images",
    "build_resource_group_name": "rg-packer"
}
----

Restera à remplacer les valeurs dans le champs idoine dans fichier packer.

Un exemple est disponible ci-dessous:

{% gist 11733d072c25c661b3237ba65dc07d69 packer.json %}